version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    commit-message:
      prefix: "feat: "
    schedule:
      interval: "daily"
    reviewers:
      - "rlespinasse"
    labels: [ ]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"
    reviewers:
      - "rlespinasse"
    labels: [ ]
