name: Build

on:
  push:
    branches:
      - v1.x
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/auto-cancel-redundant-workflow@v1
      - uses: actions/checkout@v2
      - run: make build
      - run: make test
      - name: Release this GitHub Action
        uses: rlespinasse/release-that@v1.x
        with:
          without-prefix: true
