name: Build

on:
  push:
    branches:
      - v1.x
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/auto-cancel-redundant-workflow@v1
      - uses: actions/checkout@v2
      - run: make build
      - run: make test
      - uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 17.4.0
          branches: |
            [
              'v1.x'
            ]
          extra_plugins: |
            @semantic-release/changelog@5.0.1
            @semantic-release/git@9.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
